name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore SaaS-MultiTenant-Starter.sln
      - name: Build
        run: dotnet build SaaS-MultiTenant-Starter.sln --no-restore --configuration Release
      - name: Test
        run: dotnet test SaaS-MultiTenant-Starter.sln --no-restore --configuration Release 